### ISSUE TITLE
Memory leak caused by invalid WKNavigationDelegateEvents

### ISSUE THREAD

**Issue by monibu1548** [RxSwiftCommunity/RxWebKit#38]
I am using RxWebKit 0.3.7 by Cocoapod 1.6.3, Xcode 11.1

While using RxWebkit, if the UINavigationDelegate observable is subcribed, the deinit is not called.

As a result of finding the cause, we found that the use of the "navigationEventWith" and "navigationFailEventWith" functions in the "WKNavigationDelegateEvents+Rx.swift" file resulted in circular reference.

**Comment by freak4pc** [comment]
Released in 1.0.2
