### ISSUE TITLE
Hello! Why you guys observe URL changes through KVO?

### ISSUE THREAD

**Issue by Calvin-Huang** [RxSwiftCommunity/RxWebKit#5]
I'm just curious about why use KVO instead of trigger observer from webView delegate implement.
My friends always said: RxSwift is slow because Swift bridges to Objc.

And I found a issue and PR attempt to put this function into RxCocoa.
Why the code is not in the repo anymore?
[issue-838](https://github.com/ReactiveX/RxSwift/issues/838)

I'm still wondering about which way is better.

Thanks for your answer !!

**Comment by mokumoku** [comment]
Hi @Calvin-Huang ,
I have no idea about which is better because I have never compare KVO and delegate.

Now RxWebKit uses KVO.
The reason is it is easy way to implement URL observing.

By the way I want to observe WKWebViewDelegate using RxSwift in the future 😀
