### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by patrickbdev** [RxSwiftCommunity/RxWebKit#7]
The latest version of RxWebKit on Cocoapods is 0.3.3 which isn't installable with RxSwift/RxCocoa 3.2.0. We're needing to reference the latest commit in our podfile to get it installing.
Could a new podspec release be done?
Same issue as RxMKMapView https://github.com/RxSwiftCommunity/RxMKMapView/issues/20

**Comment by mokumoku** [comment]
Hi @patrickbdev 
podspec was updated by #8 
please use version 0.3.4!

thanks!

**Comment by patrickbdev** [comment]
Thanks @mokumoku, really appreciated!
