### ISSUE TITLE
update to swift4

### ISSUE THREAD

**Issue by reshadf** [RxSwiftCommunity/RxWebKit#9]
Is there an update planned for Swift4?

**Comment by freak4pc** [comment]
If the owner of the Repo won't take care of this soon I'll fix it up in a separate branch 👍

**Comment by mokumoku** [comment]
I have not tried Swift 4 yet.
If anyone fix up to Swift 4 please create new branch! 🙏

**Comment by mokumoku** [comment]
Now this repo is updated to Swift 4 via #12 and so on.

Please use `0.3.5` release tag.
Thanks!
